alias abc="streamlink \"https://content-aeuf1.uplynk.com/channel/3324f2467c414329b3b0cc5cd987b6be/g.m3u8?rays=hjigfedcba&ad.flex=15&ad.access_level=0&expand=drmOff&v=3&ad.adunit=/abc-news/abcnews.com/web/video&ad.vast3=1&ad.vid=$program_id&ad=abcnews_live&ad.pp=datg-live-vdms&ad.v=2&ad.&pbs=c00d55016c0a4fa98c29f2565d337113\""
alias abc_australia_radio="mpv http://www.abc.net.au/res/streaming/audio/mp3/news_radio.pls"
alias africanews="streamlink https://www.youtube.com/channel/UC1_E8NeF5QHY2dtdLRBCCLA/live $*"
alias aljazeera="streamlink https://www.youtube.com/watch?v=gCNeDWCI0vo $*"
alias animals_channel="streamlink https://pluto.tv/en/live-tv/pluto-tv-animals-gb-1 $*"
alias arise_news="streamlink https://www.youtube.com/watch?v=p1uG49yAmBI $*"
alias bbc_ws="mpv https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8"
alias bbciplayer_live="bash $HOME/scripts/streaming/bbciplayer_live.sh"
alias bloomberg_europe="streamlink bloomberg.com/live/europe $*"
alias cbc="bash $HOME/scripts/streaming/cbc.sh"
alias cbla="mpv http://playerservices.streamtheworld.com/pls/CBLAFM_CBC.pls"
alias cbsnews="streamlink https://pluto.tv/en/live-tv/cbs-news-gb $*"
alias cgtn="streamlink https://live.cgtn.com/1000/prog_index.m3u8 $*"
alias cheddarnews="streamlink https://pluto.tv/en/live-tv/cheddar-gb $*"
alias cinemax="bash $HOME/scripts/streaming/cinemax.sh"
alias classicfm="mpv http://media-sov.musicradio.com/ClassicFMMP3"
alias cnbc="streamlink https://cdn-fr1-eu.lncnetworks.host/hls/cnbc_live/index.m3u8 $*"
alias cnn="streamlink https://turnerlive.akamaized.net/hls/live/586497/cnngo/cnni/master.m3u8 $*"
alias cspan1="mpv https://26233.live.streamtheworld.com/CSPAN1.mp3"
alias cspan2="mpv https://26233.live.streamtheworld.com/CSPAN2.mp3"
alias cspan3="mpv https://26233.live.streamtheworld.com/CSPAN3.mp3"
alias cspan="mpv https://26233.live.streamtheworld.com/CSPANRADIO.mp3"
alias cspan_radio="cmd.exe /c start msedge /new-window \"https://www.c-span.org/radio/\""
alias democracynow="bash $HOME/scripts/streaming/democracynow.sh"
alias dw="streamlink https://www.youtube.com/watch?v=pqabxBKzZ6M $*"
alias euronews="streamlink https://www.youtube.com/watch?v=pykpO5kQJ98 $*"
alias fox_business="bash $HOME/scripts/streaming/fox_business.sh"
alias fox_news="streamlink https://fox-foxnewsnow-samsungus.amagi.tv/playlist720p.m3u8 $*"
alias france24="streamlink https://www.youtube.com/watch?v=h3MuIUNCCzI $*"
alias gbnews="streamlink https://www.youtube.com/watch?v=8WX6YL9JnLw $*"
alias getfactual="streamlink https://pluto.tv/en/live-tv/get-factual-gb $*"
alias india_today="streamlink https://feeds.intoday.in/hltapps/api/master.m3u8 $*"
alias lbc="mpv http://media-ice.musicradio.com/LBCLondonMP3Low"
alias msnbc="bash $HOME/scripts/streaming/msnbc.sh"
alias nbc="streamlink https://d2gjhy8g9ziabr.cloudfront.net/v1/manifest/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod-samsungtvplus-stitched/114bb72d-ef6d-4533-bbc5-a9eba4d88731/3.m3u8 $*"
alias newsmax="streamlink https://nmxlive.akamaized.net/hls/live/529965/Live_1/index.m3u8 $*"
alias nhk="streamlink https://cdn.nhkworld.jp/www11/nhkworld-tv/global/2003458/live.m3u8 $*"
alias pbs_america="streamlink https://pbs-samsunguk.amagi.tv/playlist720-p.m3u8 $*"
alias premier="mpv https://pcr.streamguys1.com/pcrnational-96k.aac"
alias python="/home/linuxbrew/.linuxbrew/bin/python3 $*"
alias radio4="mpv https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_radio_fourfm.m3u8"
alias sky_news="streamlink https://www.youtube.com/watch?v=9Auq9mYxFEE $*"
alias spacechannel="streamlink https://pluto.tv/en/live-tv/pluto-tv-space-gb $*"
alias stv="streamlink https://player.stv.tv/live/stv $*"
alias times_radio="mpv http://www.radiofeeds.net/playlists/wgtimesradio.m3u"
alias trtworld="streamlink https://www.youtube.com/watch?v=5VF4aor94gw $*"
alias tv5monde="streamlink https://europe.tv5monde.com/en/live?timezone=Europe/London $*"
alias twitch="streamlink twitch.tv/$*"
alias voa="mpv http://voa-28.akacast.akamaistream.net/7/54/322040/v1/ibb.akacast.akamaistream.net/voa-28"
alias voyager_documentaries="streamlink https://pluto.tv/en/live-tv/voyager-documentaries-gb $*"
alias wnpr="mpv https://playerservices.streamtheworld.com/api/livestream-redirect/WNPRFM.mp3"
alias wnyc="mpv https://fm939.wnyc.org/wnycfm-web"
alias worldsgreatest="streamlink https://pluto.tv/en/live-tv/worlds-greatest-gb $*"
alias wrn="mpv http://streaming.edmradio.online:8025/WRN-E.m3u"
